/* Generated by tools/gen_vectors.py from the spec's vectors.json. Do not edit. */
#ifndef TANDEM_VECTORS_H
#define TANDEM_VECTORS_H
#include <stddef.h>
#include <stdint.h>
#define VEC_K 32u
static const uint32_t VEC_KEY[4] = {0x00000001u, 0x00000002u, 0x00000003u, 0x00000004u};
static const struct { uint32_t o[4], h[4], o_out[4], h_out[4]; } VEC_T[] = {
    {{0x00000001u, 0x00000002u, 0x00000003u, 0x00000004u}, {0x00000005u, 0x00000006u, 0x00000007u, 0x00000008u}, {0x00000017u, 0x00150007u, 0x00000001u, 0x00050008u}, {0x9e377ca9u, 0x0000e006u, 0x02000007u, 0x00001820u}},
    {{0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u}, {0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u}, {0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u}, {0x9e3779b9u, 0x00000000u, 0x00000000u, 0x00000000u}},
};
static const struct { uint64_t counter; uint32_t o[4], h[4]; } VEC_F[] = {
    {0u, {0x472bef12u, 0xc0977c66u, 0xd330ac3au, 0xb11a020du}, {0xbfa0b6bau, 0xecdbc48eu, 0xf1989116u, 0xc2374d96u}},
    {1u, {0xb777c10cu, 0x2f6b5a5du, 0x67a9ce03u, 0x7de06a50u}, {0xd0c2dc4fu, 0xe1e50e0fu, 0x89efc72cu, 0x6e82b062u}},
};
static const struct { uint64_t first_word; uint32_t words[4]; } VEC_STREAM[] = {
    {0u, {0x0a5bcb90u, 0x6dfe98bcu, 0x9612198au, 0xac115fd8u}},
    {4u, {0x33f598d7u, 0xb5c280cau, 0x7a8e7b99u, 0x8c362290u}},
    {32u, {0x9da7bac0u, 0x4aca79ebu, 0xbeb1f65au, 0xe2f0d5a1u}},
};
static const struct { uint64_t index; double value; } VEC_F64[] = {
    {0u, 0.4296660861094629},
    {16u, 0.2921520424112306},
};
static const struct { uint64_t index; float value; } VEC_F32[] = {
    {2u, 0.58621365f},
};
static const struct { uint64_t index; int value; } VEC_BOOL[] = {
    {0u, 0},
    {1u, 0},
    {2u, 0},
    {3u, 0},
    {4u, 1},
    {5u, 0},
    {6u, 0},
    {7u, 1},
    {128u, 1},
};
static const uint32_t VEC_SPLIT0[4] = {0xe256e9a1u, 0x5020f806u, 0x3bd3f7dcu, 0x5328763du};
static const uint32_t VEC_SPLIT1[4] = {0xa9ea3f0bu, 0x47f97af0u, 0xd1844c53u, 0x97e9cee2u};
static const uint32_t VEC_FORK0[4] = {0x67fd37c5u, 0x9dc0b8c6u, 0x4e3bd55eu, 0xaf3f2216u};
static const uint32_t VEC_PURPOSE7[4] = {0x8048398fu, 0x1678e814u, 0xd8823983u, 0xc4b1045cu};
#define VEC_SEED 42u
static const uint32_t VEC_SEED_KEY[4] = {0x421d21ebu, 0x32d31777u, 0x62e7564bu, 0xdf2bdf82u};
static const struct { uint64_t index; double value; } VEC_SEED_F64[] = {
    {0u, 0.9829130398628935},
    {2u, 0.47759300283385586},
    {16u, 0.9692135305890753},
};
static const struct { uint64_t index; uint32_t value; } VEC_SEED_U32[] = {
    {0u, 0x05e80cecu},
};
static const double VEC_CHOICE_W0[4] = {1.0, 2.0, 3.0, 4.0};
static const uint64_t VEC_CHOICE_CUT0[4] = {0x0800000000000000u, 0x1000000000000000u, 0x0c00000000000000u, 0x1400000000000000u};
static const uint32_t VEC_CHOICE_ALIAS0[4] = {2u, 3u, 3u, 3u};
static const double VEC_CHOICE_W1[1] = {0.25};
static const uint64_t VEC_CHOICE_CUT1[1] = {0x4000000000000000u};
static const uint32_t VEC_CHOICE_ALIAS1[1] = {0u};
static const double VEC_CHOICE_W2[9] = {2.0, 0.1, 0.0, 1.0, 5e-324, 0.7, 3.8, 0.001, 0.3};
static const uint64_t VEC_CHOICE_CUT2[9] = {0x0581ef293003a450u, 0x01999999999999a0u, 0x0000000000000000u, 0x077619f0fb38a9a8u, 0x0000000000000001u, 0x0b33333333333300u, 0x0e0bd53834cafaa8u, 0x0004189374bc6a7fu, 0x04ccccccccccccc0u};
static const uint32_t VEC_CHOICE_ALIAS2[9] = {3u, 0u, 0u, 6u, 6u, 6u, 6u, 6u, 6u};
static const double VEC_CHOICE_W3[3] = {5e-324, 1.5e-323, 0.0};
static const uint64_t VEC_CHOICE_CUT3[3] = {0x1000000000000000u, 0x1555555555555556u, 0x0000000000000000u};
static const uint32_t VEC_CHOICE_ALIAS3[3] = {1u, 1u, 1u};
static const double VEC_CHOICE_W4[3] = {1e+308, 1.0, 1.7976931348623157e+308};
static const uint64_t VEC_CHOICE_CUT4[3] = {0x02669a07e50b80abu, 0x0000000000000001u, 0x21334d03f285bf56u};
static const uint32_t VEC_CHOICE_ALIAS4[3] = {2u, 0u, 2u};
static const struct { const double *w; const uint64_t *cut; const uint32_t *alias; size_t m;
    uint64_t capacity; uint32_t indices[16]; } VEC_CHOICE[] = {
    {VEC_CHOICE_W0, VEC_CHOICE_CUT0, VEC_CHOICE_ALIAS0, 4u, 0x1400000000000000u, {1u, 3u, 3u, 2u, 1u, 1u, 3u, 0u, 1u, 1u, 0u, 3u, 3u, 1u, 3u, 3u}},
    {VEC_CHOICE_W1, VEC_CHOICE_CUT1, VEC_CHOICE_ALIAS1, 1u, 0x4000000000000000u, {0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u}},
    {VEC_CHOICE_W2, VEC_CHOICE_CUT2, VEC_CHOICE_ALIAS2, 9u, 0x0e0bd53834cafaa8u, {6u, 6u, 6u, 6u, 0u, 3u, 6u, 0u, 6u, 3u, 3u, 6u, 6u, 6u, 6u, 6u}},
    {VEC_CHOICE_W3, VEC_CHOICE_CUT3, VEC_CHOICE_ALIAS3, 3u, 0x1555555555555556u, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 0u, 1u, 1u, 0u, 1u, 1u, 1u, 1u, 1u}},
    {VEC_CHOICE_W4, VEC_CHOICE_CUT4, VEC_CHOICE_ALIAS4, 3u, 0x21334d03f285bf56u, {0u, 2u, 2u, 0u, 2u, 0u, 2u, 2u, 0u, 0u, 2u, 2u, 2u, 0u, 2u, 2u}},
};
#endif
