// Writes the cross-check fixtures of tests/test_api.c from tandem-cuda's core.hpp, the shared
// device core, so that every port that follows it returns the same values. The Float64 normals
// come from this library instead, which is their reference.
//
//   make cross        regenerates tests/cross_below.h, tests/cross_normal.h and the others
//
// The bounded and normal cases start from Rng(42) after one bit draw, which leaves the position
// unaligned.
#include <cinttypes>
#include <cstdio>
#include <cstring>
#include <vector>

#include "../tandem.h"
#include "../tandem_normal_tables.h"
#include "tandem/core.hpp"

static const uint32_t RANGES32[] = {1u, 2u, 6u, 1000u, 0xc0000001u, 0xffffffffu};
static const uint64_t RANGES64[] = {1ull,
                                    3ull,
                                    1000000000000ull,
                                    0xc000000000000001ull,
                                    0xffffffffffffffffull};
constexpr int COUNT = 64;

static void below() {
    std::printf("/* Generated by tools/gen_cross.cpp from tandem-cuda core.hpp. Do not edit. */\n");
    std::printf("#define CROSS_COUNT %d\n\n", COUNT);
    std::printf("static const struct {\n    uint32_t n;\n    uint32_t want[CROSS_COUNT];\n"
                "    uint64_t end_pos;\n} CROSS_U32[] = {\n");
    for (uint32_t n : RANGES32) {
        tandem::Rng g(42);
        g.bit();
        std::printf("    {%" PRIu32 "u,\n     {", n);
        for (int i = 0; i < COUNT; i++)
            std::printf("%s%" PRIu32 "u", i ? (i % 8 ? ", " : ",\n      ") : "", g.urand(n));
        std::printf("},\n     %" PRIu64 "u},\n", g.position());
    }
    std::printf("};\n\nstatic const struct {\n    uint64_t n;\n    uint64_t want[CROSS_COUNT];\n"
                "    uint64_t end_pos;\n} CROSS_U64[] = {\n");
    for (uint64_t n : RANGES64) {
        tandem::Rng g(42);
        g.bit();
        std::printf("    {%" PRIu64 "ull,\n     {", n);
        for (int i = 0; i < COUNT; i++)
            std::printf("%s%" PRIu64 "ull", i ? (i % 4 ? ", " : ",\n      ") : "", g.urand64(n));
        std::printf("},\n     %" PRIu64 "u},\n", g.position());
    }
    std::printf("};\n");
}

// The parallel fills of core.hpp: element i maps draw i and a rejection retries on a fallback
// generator keyed by the global draw index, the aligned start position over the draw width plus
// i. Rejections are common for the ranges above 2^31 and 2^63. The starts are 0, 1 bit (aligned up
// to 32 or 64) and 12345 bits, so that the draw index is not the element index.
static const uint64_t STARTS[] = {0ull, 1ull, 12345ull};

static void fill_below() {
    std::printf("/* Generated by tools/gen_cross.cpp from tandem-cuda core.hpp. Do not edit. */\n");
    std::printf("static const struct {\n    uint64_t start;\n    uint32_t n;\n"
                "    uint32_t want[CROSS_COUNT];\n    uint64_t end_pos;\n} CROSS_FILL_U32[] = {\n");
    for (uint64_t start : STARTS)
        for (uint32_t n : RANGES32) {
            tandem::Rng g(42);
            g.set_position(start);
            tandem::Key k = g.key();
            uint64_t first = (start + 31) / 32;
            std::printf("    {%" PRIu64 "ull, %" PRIu32 "u,\n     {", start, n);
            for (int i = 0; i < COUNT; i++)
                std::printf("%s%" PRIu32 "u", i ? (i % 8 ? ", " : ",\n      ") : "",
                            tandem::below_u32(g.urand(), n, k.w, g.chunk_length(), first + (uint64_t)i));
            std::printf("},\n     %" PRIu64 "u},\n", g.position());
        }
    std::printf("};\n\nstatic const struct {\n    uint64_t start;\n    uint64_t n;\n"
                "    uint64_t want[CROSS_COUNT];\n    uint64_t end_pos;\n} CROSS_FILL_U64[] = {\n");
    for (uint64_t start : STARTS)
        for (uint64_t n : RANGES64) {
            tandem::Rng g(42);
            g.set_position(start);
            tandem::Key k = g.key();
            uint64_t first = (start + 63) / 64;
            std::printf("    {%" PRIu64 "ull, %" PRIu64 "ull,\n     {", start, n);
            for (int i = 0; i < COUNT; i++)
                std::printf("%s%" PRIu64 "ull", i ? (i % 4 ? ", " : ",\n      ") : "",
                            tandem::below_u64(g.urand64(), n, k.w, g.chunk_length(), first + (uint64_t)i));
            std::printf("},\n     %" PRIu64 "u},\n", g.position());
        }
    std::printf("};\n");
}

// The kind of element e of the Float64 normal fill from position 0: a draw inside the inner
// rectangles, or a miss that the wedge test accepts, rejects, or one in the tail layer.
enum Kind { FAST, WEDGE_ACCEPT, WEDGE_REJECT, TAIL };
static const char *const KIND_NAMES[] = {"fast", "wedge accepted", "wedge rejected", "tail"};

static Kind kind(uint64_t r, double z) {
    uint64_t ra = r >> 11;
    double x = (double)(int64_t)ra * ZIG_W[r & (2 * ZIG_LAYERS - 1)];
    if (ra < ZIG_K[r & (ZIG_LAYERS - 1)]) return FAST;
    if ((r & (ZIG_LAYERS - 1)) == 0) return TAIL;
    return z == x ? WEDGE_ACCEPT : WEDGE_REJECT;
}

// Float64 normals: fills of tandem-c from the key of seed 42. Three rows start at unaligned
// positions and the others put each kind of miss at element MISS_AT, unaligned too.
constexpr int MISS_AT = 20;

static void normal() {
    const int scan = 1 << 20;
    std::vector<uint64_t> raw(scan);
    std::vector<double> z(scan);
    tandem_rng s = tandem_seed(42, 0, 0);
    tandem_fill_u64(&s, raw.data(), scan);
    s = tandem_seed(42, 0, 0);
    tandem_fill_normal_f64(&s, z.data(), scan);
    std::vector<uint64_t> starts = {0, 1, 12345};
    std::vector<int> at_kind = {-1, -1, -1};
    for (int k = WEDGE_ACCEPT; k <= TAIL; k++)
        for (int e = MISS_AT + 1; e < scan; e++)
            if (kind(raw[e], z[e]) == k) {
                starts.push_back(64 * (uint64_t)(e - MISS_AT) - 63);
                at_kind.push_back(k);
                break;
            }

    std::printf("/* Generated by tools/gen_cross.cpp, Float64 normals from tandem-c and Float32 normals "
                "from\n * tandem-cuda core.hpp. Do not edit. */\n");
    std::printf("#define CROSS_NORMAL_COUNT %d\n\n", COUNT);
    std::printf("/* Float64 ziggurat fills of %d elements from the key of seed 42 at each start, which "
                "the fill\n * aligns up to 64 bits. Element %d of the last rows is a miss:", COUNT, MISS_AT);
    for (size_t r = 3; r < starts.size(); r++)
        std::printf("%s %s", r > 3 ? "," : "", KIND_NAMES[at_kind[r]]);
    std::printf(". */\nstatic const struct {\n    uint64_t start;\n    double want[CROSS_NORMAL_COUNT];\n"
                "    uint64_t end_pos;\n} CROSS_NORMAL[] = {\n");
    for (uint64_t start : starts) {
        tandem_rng g = tandem_seed(42, 0, 0);
        double want[COUNT];
        tandem_set_position(&g, start);
        tandem_fill_normal_f64(&g, want, COUNT);
        std::printf("    {%" PRIu64 "ull,\n     {", start);
        for (int i = 0; i < COUNT; i++) std::printf("%s%.17g", i ? (i % 4 ? ", " : ",\n      ") : "", want[i]);
        std::printf("},\n     %" PRIu64 "u},\n", tandem_position(&g));
    }
    std::printf("};\n\n");

    // On a host, core.hpp's normalf2 runs the explicit-fma loop of tandem.c, so the values are
    // exact. 9 significant digits round-trip every float.
    tandem::Rng f(42);
    f.bit();
    std::printf("/* Float32 Box-Muller pairs of seed 42 after one bit draw: element 2i is the cos half, "
                "2i + 1\n * the sin half. */\n");
    std::printf("static const float CROSS_NORMALF[2 * CROSS_NORMAL_COUNT] = {");
    for (int i = 0; i < COUNT; i++) {
        auto p = f.normalf2();
        std::printf("%s%.9gf, %.9gf", i ? ",\n    " : "\n    ", p.z0, p.z1);
    }
    std::printf("\n};\nstatic const uint64_t CROSS_NORMALF_END_POS = %" PRIu64 "u;\n", f.position());
}

// Exponentials from Rng(42) at several start positions, unaligned ones included. core.hpp's
// exponential_f64 and exponential_f32 run the polynomial logarithm of tandem.c, so the values are
// exact on every host and device.
static const uint64_t EXP_STARTS[] = {0ull, 1ull, 77ull, 12345ull, 1ull << 30};

static void exponential() {
    std::printf("/* Generated by tools/gen_cross.cpp from tandem-cuda core.hpp. Do not edit. */\n");
    std::printf("#define CROSS_EXPONENTIAL_COUNT %d\n\n", COUNT);
    std::printf("static const struct {\n    uint64_t start;\n    double want[CROSS_EXPONENTIAL_COUNT];\n"
                "    uint64_t end_pos;\n} CROSS_EXPONENTIAL[] = {\n");
    for (uint64_t start : EXP_STARTS) {
        tandem::Rng g(42);
        g.set_position(start);
        std::printf("    {%" PRIu64 "ull,\n     {", start);
        for (int i = 0; i < COUNT; i++)
            std::printf("%s%.17g", i ? (i % 4 ? ", " : ",\n      ") : "", g.exponential());
        std::printf("},\n     %" PRIu64 "u},\n", g.position());
    }
    std::printf("};\n\nstatic const struct {\n    uint64_t start;\n    float want[CROSS_EXPONENTIAL_COUNT];\n"
                "    uint64_t end_pos;\n} CROSS_EXPONENTIALF[] = {\n");
    for (uint64_t start : EXP_STARTS) {
        tandem::Rng g(42);
        g.set_position(start);
        std::printf("    {%" PRIu64 "ull,\n     {", start);
        for (int i = 0; i < COUNT; i++)
            std::printf("%s%.9gf", i ? (i % 6 ? ", " : ",\n      ") : "", (double)g.exponentialf());
        std::printf("},\n     %" PRIu64 "u},\n", g.position());
    }
    std::printf("};\n");
}

int main(int argc, char **argv) {
    if (argc == 2 && !std::strcmp(argv[1], "below")) below();
    else if (argc == 2 && !std::strcmp(argv[1], "fill_below")) fill_below();
    else if (argc == 2 && !std::strcmp(argv[1], "normal")) normal();
    else if (argc == 2 && !std::strcmp(argv[1], "exponential")) exponential();
    else {
        std::fprintf(stderr, "usage: gen_cross below|fill_below|normal|exponential\n");
        return 2;
    }
    return 0;
}
