// Writes the cross-check fixtures of tests/test_api.c from tandem-cuda's core.hpp, the shared
// device core, so that every port that follows it returns the same values.
//
//   make cross        regenerates tests/cross_below.h and tests/cross_normal.h
//
// Each case starts from Rng(42) after one bit draw, which leaves the position unaligned.
#include <cinttypes>
#include <cstdio>
#include <cstring>

#include "tandem/core.hpp"

static const uint32_t RANGES32[] = {1u, 2u, 6u, 1000u, 0xc0000001u, 0xffffffffu};
static const uint64_t RANGES64[] = {1ull,
                                    3ull,
                                    1000000000000ull,
                                    0xc000000000000001ull,
                                    0xffffffffffffffffull};
constexpr int COUNT = 64;

static void below() {
    std::printf("/* Generated by tools/gen_cross.cpp from tandem-cuda core.hpp. Do not edit. */\n");
    std::printf("#define CROSS_COUNT %d\n\n", COUNT);
    std::printf("static const struct {\n    uint32_t n;\n    uint32_t want[CROSS_COUNT];\n"
                "    uint64_t end_pos;\n} CROSS_U32[] = {\n");
    for (uint32_t n : RANGES32) {
        tandem::Rng g(42);
        g.bit();
        std::printf("    {%" PRIu32 "u,\n     {", n);
        for (int i = 0; i < COUNT; i++)
            std::printf("%s%" PRIu32 "u", i ? (i % 8 ? ", " : ",\n      ") : "", g.urand(n));
        std::printf("},\n     %" PRIu64 "u},\n", g.position());
    }
    std::printf("};\n\nstatic const struct {\n    uint64_t n;\n    uint64_t want[CROSS_COUNT];\n"
                "    uint64_t end_pos;\n} CROSS_U64[] = {\n");
    for (uint64_t n : RANGES64) {
        tandem::Rng g(42);
        g.bit();
        std::printf("    {%" PRIu64 "ull,\n     {", n);
        for (int i = 0; i < COUNT; i++)
            std::printf("%s%" PRIu64 "ull", i ? (i % 4 ? ", " : ",\n      ") : "", g.urand64(n));
        std::printf("},\n     %" PRIu64 "u},\n", g.position());
    }
    std::printf("};\n");
}

// The parallel fills of core.hpp: element i maps draw i and a rejection retries on a fallback
// generator keyed by the global draw index, the aligned start position over the draw width plus
// i. Rejections are common for the ranges above 2^31 and 2^63. The starts are 1 bit (aligned up
// to 32 or 64) and 12345 bits, so that the draw index is not the element index.
static const uint64_t STARTS[] = {1ull, 12345ull};

static void fill_below() {
    std::printf("/* Generated by tools/gen_cross.cpp from tandem-cuda core.hpp. Do not edit. */\n");
    std::printf("static const struct {\n    uint64_t start;\n    uint32_t n;\n"
                "    uint32_t want[CROSS_COUNT];\n    uint64_t end_pos;\n} CROSS_FILL_U32[] = {\n");
    for (uint64_t start : STARTS)
        for (uint32_t n : RANGES32) {
            tandem::Rng g(42);
            g.set_position(start);
            tandem::Key k = g.key();
            uint64_t first = (start + 31) / 32;
            std::printf("    {%" PRIu64 "ull, %" PRIu32 "u,\n     {", start, n);
            for (int i = 0; i < COUNT; i++)
                std::printf("%s%" PRIu32 "u", i ? (i % 8 ? ", " : ",\n      ") : "",
                            tandem::below_u32(g.urand(), n, k.w, g.chunk_length(), first + (uint64_t)i));
            std::printf("},\n     %" PRIu64 "u},\n", g.position());
        }
    std::printf("};\n\nstatic const struct {\n    uint64_t start;\n    uint64_t n;\n"
                "    uint64_t want[CROSS_COUNT];\n    uint64_t end_pos;\n} CROSS_FILL_U64[] = {\n");
    for (uint64_t start : STARTS)
        for (uint64_t n : RANGES64) {
            tandem::Rng g(42);
            g.set_position(start);
            tandem::Key k = g.key();
            uint64_t first = (start + 63) / 64;
            std::printf("    {%" PRIu64 "ull, %" PRIu64 "ull,\n     {", start, n);
            for (int i = 0; i < COUNT; i++)
                std::printf("%s%" PRIu64 "ull", i ? (i % 4 ? ", " : ",\n      ") : "",
                            tandem::below_u64(g.urand64(), n, k.w, g.chunk_length(), first + (uint64_t)i));
            std::printf("},\n     %" PRIu64 "u},\n", g.position());
        }
    std::printf("};\n");
}

// log and cos differ in the last place between libms, so the normals are stored as decimal
// text with 17 digits and compared within a relative tolerance.
static void normal() {
    tandem::Rng g(42);
    g.bit();
    std::printf("/* Generated by tools/gen_cross.cpp from tandem-cuda core.hpp. Do not edit. */\n");
    std::printf("#define CROSS_NORMAL_COUNT %d\n\n", COUNT);
    std::printf("/* Pairs: element 2i is the cos half, 2i + 1 the sin half. */\n");
    std::printf("static const double CROSS_NORMAL[2 * CROSS_NORMAL_COUNT] = {");
    for (int i = 0; i < COUNT; i++) {
        auto p = g.normal2();
        std::printf("%s%.17g, %.17g", i ? ",\n    " : "\n    ", p.z0, p.z1);
    }
    std::printf("\n};\nstatic const uint64_t CROSS_NORMAL_END_POS = %" PRIu64 "u;\n\n", g.position());

    tandem::Rng f(42);
    f.bit();
    std::printf("static const float CROSS_NORMALF[2 * CROSS_NORMAL_COUNT] = {");
    for (int i = 0; i < COUNT; i++) {
        auto p = f.normalf2();
        std::printf("%s%.9gf, %.9gf", i ? ",\n    " : "\n    ", p.z0, p.z1);
    }
    std::printf("\n};\nstatic const uint64_t CROSS_NORMALF_END_POS = %" PRIu64 "u;\n", f.position());
}

int main(int argc, char **argv) {
    if (argc == 2 && !std::strcmp(argv[1], "below")) below();
    else if (argc == 2 && !std::strcmp(argv[1], "fill_below")) fill_below();
    else if (argc == 2 && !std::strcmp(argv[1], "normal")) normal();
    else {
        std::fprintf(stderr, "usage: gen_cross below|fill_below|normal\n");
        return 2;
    }
    return 0;
}
